apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  # 可以并行任务数量，默认1
  parallelism: 3
  completions: 3
  # Pod完成模式，NonIndexed（数量达到completions推出，默认），Indexed
  # Indexed模式：会被设置为Pod服务名
  # - 设置Pod名称：<Job Name>-<索引序号>-<随机字符串>
  # - 设置Annotation "batch.kubernetes.io/job-completion-index": <索引序号>
  # - 设置Label "batch.kubernetes.io/job-completion-index": <索引序号>，从K8s v1.28 需要开启PodIndexLabel特性门控
  # - 在容器内注入环境变量JOB_COMPLETION_INDEX，值为索引序号
  # - 与一个Headless Service搭配使用，Pod网络访问域名将被设置为<$(job_name)-$(index)>.<headless-service-name>，并且设置正确的DNS记录
  completionMode: NonIndexed
  # 失败任务的最大重试次数上限
  backoffLimit: 4
  # Pod最长运行时间，单位s
  activeDeadlineSeconds: 2
  # 用于设置TTL Controller自动清理机制
  ttlSecondsAfterFinished: 10
  # K8s v1.28 开始支持，Pod失效时候，支持Ignore、FailJob、Count或FailIndex
  podFailurePolicy:
    # 按照顺序对多个规则进行评估，一旦某个规则匹配，则立即停止评估后续规则
    rules:
      # FailJob: 立即终止Job并且标记为Failed，同时停止全部未终止的Pod
      # Ignore: 重建一个新的Pod，同时不计入backoffLimit
      # FailIndex： 在使用索引的情况下，将失效索引的Pod设置为不再重试
      - action: FailJob
        # onPodConditions:根据Pod的情况，采用什么样子的action
        # onExitCode: 根据Pod退出码，采用什么样子的action
        onPodConditions:
          - type: Disrupted
            status: "true"

  # K8s v1.28 开始支持，Pod失效时候,替换策略
  podReplacementPolicy: OnPodFailure
  # K8s v1.27 引入手动设置标签选择器
  manualSelector: true
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hello
          image: busybox
          command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
